# sudo required to have Docker
sudo: required
language: generic

services:
  # installs Docker into our little container
  - docker

before_install:
  - docker build -t piotrlipiarz/docker-react -f Dockerfile.dev .

script:
  # ENvs -> https://docs.docker.com/engine/reference/run/#env-environment-variables
  # `CI=true` exists test runner
  # https://create-react-app.dev/docs/running-tests/#linux-macos-bash
  - docker run -e CI=true piotrlipiarz/docker-react npm run test

#  language: generic
  # 
  # 
  # 
